language: cpp
compiler:
    - gcc

before_install:
    - yes | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - yes | sudo apt-get install gcc-4.9
    - yes | sudo apt-get install g++-4.9
    - sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++ -f
    - sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc -f
    - gcc --version
    - sudo apt-get install dos2unix

script:
    - PROJECT_ROOT=`pwd` 
    - ./build.sh

os:
    - linux

sudo: required
